### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by jasonyeh-dev** [achen353/Taiwanese-Traffic-Object-Detection#2]
Excuse me!

Could you provide the link of the dataset?
I can't download it on the official website.

Thanks in advanced!

**Comment by achen353** [comment]
Hi @108618026. Thanks for your interest. As mentioned in the README, the data was provided in a competition and was not meant to be released to the public.

**Comment by sriks6711** [comment]
> Excuse me!
> 
> Could you provide the link of the dataset? I can't download it on the official website.
> 
> Thanks in advanced!


> Hi @108618026. Thanks for your interest. As mentioned in the README, the data was provided in a competition and was not meant to be released to the public.

@108618026 and @achen353 

The dataset might be available here -
https://www.kaggle.com/datasets/chienhsianghung/obj-detect (26GB)
https://www.kaggle.com/code/chienhsianghung/yolov5-for-asian-traffic-object-detection
